export const formFields = {
    firstName: '',
    lastName: '',
    age: '',
    occupation:'',
    income:0,
    expense:0,
    insuranceAndInvestment: 0,
    fixedAssets:0,
    equity:0,
    debt:0,
    cash:0,
    otherAssets:0,
    homeLoan:0,
    vehicleLoan:0,
    otherLoan:0,
    goal:'',
    goal1:'',
    goal2:'',
    goal3:'',
    goal4:'',
    currentGoalValue:0,
    currentGoalValue1:0,
    currentGoalValue2:0,
    currentGoalValue3:0,
    currentGoalValue4:0,
    yearsToGoalFulfillment:0,
    yearsToGoalFulfillment1:0,
    yearsToGoalFulfillment2:0,
    yearsToGoalFulfillment3:0,
    yearsToGoalFulfillment4:0,
    currentInvestmentForGoal:0,
    currentInvestmentForGoal1:0,
    currentInvestmentForGoal2:0,
    currentInvestmentForGoal3:0,
    currentInvestmentForGoal4:0,
    currentInvestmentRate:0,
    currentInvestmentRate1:0,
    currentInvestmentRate2:0,
    currentInvestmentRate3:0,
    currentInvestmentRate4:0,

}